### ISSUE TITLE
Cannot install from palette 

### ISSUE THREAD

**Issue by mtoko** [bonastreyair/node-red-contrib-teachable-machine#11]
Hi
I have tried to install from the palette, but there is a error which appears to be related to the canvas dependencies. I have read the other issues which may be related.
1.) Node Red 1.0.6
2.) I have tried to install canvas as root user as indicated this was possibly a permissions problem, but canvas won't even install on its own
3.) There is a similar issue with node-red-contrib-face-recognition node which also won't install

Appreciate any advice
Error message

pi@CameraPi:~/.node-red $ npm install node-red-contrib-teachable-machine
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> canvas@2.6.1 install /home/pi/.node-red/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v64-linux-glibc-arm.tar.gz
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@10.20.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.97+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/.node-red/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/pi/.node-red/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /home/pi/.node-red/node_modules/canvas
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/.node-red/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/.node-red/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/.node-red/node_modules/canvas/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.19.97+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/.node-red/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/.node-red/node_modules/canvas
node-pre-gyp ERR! node -v v10.20.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/.node-red/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/pi/.node-red/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN @teachablemachine/image@0.8.4 requires a peer of @tensorflow/tfjs@1.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1

**Comment by crxporter** [comment]
I’m getting the same issue. Running on pi 4. 

Any ideas for getting it to run?

**Comment by mtoko** [comment]
I have not been able to get it to run on a Pi, but did get it to run on a Linux PC, possibly Pi related

**Comment by bonastreyair** [comment]
For now it is not working due to the `canvas` npm module. It does not exist a pre-built package and it has problems when trying to compile it for the Raspberry Pi...

```
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@10.20.1...
```

I have not yet investigated how to make it work on a Raspberry Pi (with the compilation of the `canvas`). What I tried to git rid of the `canvas` npm package... but could not find the solution. I only use `canvas` to handle the image though... The problem here is that` teachable machine` original npm package is designed to work within a webpage not in a server making use of all global objects such as document or canvas, and with this node I can emulate that so that it behaves as webpage (making use of JDOM library)... I also wanted to get rid of that... but with no success.

Let me know if you find any solution! Thanks!

**Comment by Viggen-l** [comment]
Hi
Just tried to install from Node-red Manage Pallete on both Pi and Windows but just get this error
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/node-contrib-teachable-machine - Not found

**Comment by bonastreyair** [comment]
On Raspberry Pi it is not supported yet. Windows is supported.

GET error seems like a npm bad connection http response, not a problem of the node itself. Can you try to install it again @Viggen-l ?

**Comment by Viggen-l** [comment]
Yes know it's working on windows.
What's missing to run this on a Pi, the project i'am looking on are probably going to run on a Pi.

**Comment by ergoego** [comment]
I think the issue on the Pi comes down to fsevents - linus is not supported OS (Darwin is). 

If this dependency can be removed, then I think the Pi will work. I can get all other packages to install.

**Comment by ergoego** [comment]
https://github.com/paulmillr/chokidar maybe this can be used instead of fsevents?

**Comment by FunkyGandalf** [comment]
Thanks for working on this!  I am having the same issue, neither the npm install nor install through the palette works, both generate the same error message for me.

Is it possible to develop a specific version of the node for use on the Raspberry Pi?  Teachable Machine is a great starting idea, but currently seems rather limited to "look, my browser can tell if there's a cat in the image or not!"  But I want to actually be able to DO something with that information.  Being able to run those models on a Pi with Node Red making it easy to program the doing part (turn on GPIO pins, send text messages, etc.) would turn this from something kinda interesting to something actually super-useful.

**Comment by Viggen-l** [comment]
Teachablemachine are easy but usefull, trying it out on a production line (node-red on windows) together with Siemens PLC and it's working well so far. But yes it would be nice to be able to run it on a Pi as or maybe Siemens IoT20** hardware.

**Comment by bonastreyair** [comment]
- [New release v1.2.0](https://github.com/bonastreyair/node-red-contrib-teachable-machine/tree/v1.2.0) - compatible with Raspberry Pi and official dockerized Node-RED
