### ISSUE TITLE
Canvas dependency compilation

### ISSUE THREAD

**Issue by dceejay** [bonastreyair/node-red-contrib-teachable-machine#17]
Hi Yair, hows things ?

not really an issue per se... but the canvas dependency can be a pain to get recompiled on platforms like older Pi etc... Have you seen pureimage library - https://github.com/joshmarinacci/node-pureimage which is a canvas in pure js - so should be more portable... may be worth looking at. 

It may of course fix Issue #11.

**Comment by bonastreyair** [comment]
I'll sure take a look! Thanks 🙏!

**Comment by bonastreyair** [comment]
I just tested it out but found that teachable machine uses canvas to crop the image... and if I remove the dependancy then it doesn't work.

See this error when leaving JSDOM
```
(node:64424) UnhandledPromiseRejectionWarning: TypeError: Image or Canvas expected
    at CanvasRenderingContext2D.ctx.<computed> [as drawImage] (../node-red-contrib-teachable-machine/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:124:17)
    at Object.cropTo (../node-red-contrib-teachable-machine/node_modules/@teachablemachine/image/dist/utils/canvas.js:60:9)
```

Or see this other one without jsdom enabled
```
(node:64538) UnhandledPromiseRejectionWarning: ReferenceError: document is not defined
    at newCanvas (../node-red-contrib-teachable-machine/node_modules/@teachablemachine/image/dist/utils/canvas.js:19:31)
    at Object.cropTo (..node-red-contrib-teachable-machine/node_modules/@teachablemachine/image/dist/utils/canvas.js:43:39)
```

I think I will have to also remove the dependancy on @teachablemachine/image and just rely on raw tensorflow to make it run without any other dependancy...

**Comment by bonastreyair** [comment]
Check latest version! 

I've made many modifications but finally successfully got rid of `jsdom`, `canvas` and even `@teachablemachine/image`!

- [New release v1.2.0](https://github.com/bonastreyair/node-red-contrib-teachable-machine/tree/v1.2.0) - compatible with Raspberry Pi and official dockerized Node-RED

Thanks for the recomendation on the library! 🙏
