### ISSUE TITLE
TypeError: backend.cast is not a function

### ISSUE THREAD

**Issue by AkashSCIENTIST** [bonastreyair/node-red-contrib-teachable-machine#66]
When I used this node I am getting this error :
```
[error] TypeError: backend.cast is not a function
    at engine_1.ENGINE.runKernelFunc.x (C:\Users\akash\.node-red\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\ops\array_ops.js:139:78)
    at C:\Users\akash\.node-red\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\engine.js:542:55
    at C:\Users\akash\.node-red\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\engine.js:388:22
    at Engine.scopedRun (C:\Users\akash\.node-red\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\engine.js:398:23)
    at Engine.tidy (C:\Users\akash\.node-red\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\engine.js:387:21)
    at kernelFunc (C:\Users\akash\.node-red\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\engine.js:542:29)
    at C:\Users\akash\.node-red\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\engine.js:553:27
    at Engine.scopedRun (C:\Users\akash\.node-red\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\engine.js:398:23)
    at Engine.runKernelFunc (C:\Users\akash\.node-red\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\engine.js:551:14)
    at cast_ (C:\Users\akash\.node-red\node_modules\@tensorflow\tfjs\node_modules\@tensorflow\tfjs-core\dist\ops\array_ops.js:139:28)
```

Could anyone provide solution ?

**Comment by bonastreyair** [comment]
I would need more information to understand your problem... it seems a problem with tfjs
I recommend to install it in a new clean environment. Let me know if you encounter the same problem then.
